import { ModelViewer } from './model-viewer.js';
import { TextureEditor } from './texture-editor.js';
import { listProjects,getProject,saveProject,moveToTrash,restoreProject,deleteProjectForever,purgeExpiredTrash,estimateStorage,requestPersistentStorage,createProjectId,formatBytes } from './storage.js';
import { exportGLB,exportFBXExperimental,downloadBlob } from './exporters.js';
import { applyTranslations,toggleLanguage } from './i18n.js';

const $=id=>document.getElementById(id);
const dashboard=$('dashboard'),editorScreen=$('editor'),modelInput=$('modelFileInput'),textureInput=$('textureFileInput'),mtlInput=$('mtlFileInput');
const viewer=new ModelViewer($('viewportCanvas'));
const tex=new TextureEditor($('textureCanvas'),$('uvOverlayCanvas'),$('uvCanvasWrap'));
let project=null,activeMap='map',activeUdim=1001,autosaveTimer=null,dirty=false,compare=false;
const mapDocs=new Map();

function toast(message,type=''){const e=document.createElement('div');e.className=`toast ${type}`;e.textContent=message;$('toastHost').append(e);setTimeout(()=>e.remove(),2400);}
function status(message){$('statusMessage').textContent=message;}
function modal(html){$('modalCard').innerHTML=html;$('modalBackdrop').classList.remove('hidden');}
function closeModal(){$('modalBackdrop').classList.add('hidden');$('modalCard').innerHTML='';}
$('modalBackdrop').addEventListener('click',e=>{if(e.target===$('modalBackdrop'))closeModal();});
function markDirty(){dirty=true;$('saveState').textContent='Unsaved local changes';}
function markSaved(){dirty=false;$('saveState').textContent='Saved locally';$('autosaveStatus').textContent=`Autosave: ${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`;}
function showEditor(){dashboard.classList.add('hidden');editorScreen.classList.remove('hidden');viewer.resize();tex.resize();}
function showDashboard(){editorScreen.classList.add('hidden');dashboard.classList.remove('hidden');renderProjects();}
function fileBase(name='project'){return name.replace(/\.[^.]+$/,'').replace(/[^a-z0-9_-]+/gi,'_')||'project';}
function dataUrlToBlob(url){const [m,d]=url.split(','),mime=(m.match(/:(.*?);/)||[])[1]||'image/png',bin=atob(d),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return new Blob([a],{type:mime});}

async function renderProjects(){await purgeExpiredTrash(30);const items=await listProjects(),grid=$('projectGrid');grid.innerHTML='';$('emptyProjects').classList.toggle('hidden',items.length>0);for(const p of items){const card=document.createElement('article');card.className='project-card';card.innerHTML=`<div class="project-thumb" ${p.thumbnail?`style="background-image:url('${p.thumbnail}')"`:''}>${p.thumbnail?'':'◇'}</div><div class="project-meta"><h4></h4><p></p></div><button class="project-menu" type="button">×</button>`;card.querySelector('h4').textContent=p.name||'Untitled Project';card.querySelector('p').textContent=`${p.sourceName||'Model'} · ${new Date(p.updatedAt).toLocaleString()}`;card.addEventListener('click',()=>openProject(p.id));card.querySelector('.project-menu').addEventListener('click',async e=>{e.stopPropagation();await moveToTrash(p.id);renderProjects();});grid.append(card);}const est=await estimateStorage();if(est)$('storageMeter').textContent=`Storage: ${formatBytes(est.usage)} / ${formatBytes(est.quota)}`;}

async function newProjectWithFile(file){project={id:createProjectId(),name:fileBase(file.name),sourceName:file.name,sourceBlob:file,sourceType:file.name.split('.').pop().toLowerCase(),createdAt:Date.now(),updatedAt:Date.now(),versions:[],editorState:null,deletedAt:null};showEditor();$('projectNameInput').value=project.name;await loadModel(file);startAutosave();}
async function openProject(id){const p=await getProject(id);if(!p)return;project=p;showEditor();$('projectNameInput').value=p.name||'Untitled Project';if(p.sourceBlob)await loadModel(new File([p.sourceBlob],p.sourceName||'model',{type:p.sourceBlob.type}));if(p.textureBlob){const f=new File([p.textureBlob],p.textureName||'texture.png',{type:p.textureBlob.type||'image/png'});await loadTextureFiles([f],false);}markSaved();startAutosave();}

function startAutosave(){clearInterval(autosaveTimer);autosaveTimer=setInterval(()=>{if(dirty)saveCurrentProject();},15000);}
async function saveCurrentProject(){if(!project)return;project.name=$('projectNameInput').value.trim()||'Untitled Project';project.thumbnail=viewer.getScreenshotDataUrl();project.textureBlob=await tex.toBlob();project.textureName=`${activeMap}-${activeUdim}.png`;project.versions=tex.versions.slice(-20).map(v=>({id:v.id,name:v.name,time:v.time,data:v.canvas.toDataURL('image/png')}));project=await saveProject(project);markSaved();}
window.addEventListener('beforeunload',()=>{if(dirty)saveCurrentProject();});

async function loadModel(file){if(!file)return;try{status(`Loading ${file.name}`);if(file.size>300*1024*1024)toast('Large model detected. Performance may be affected.');const info=await viewer.loadFile(file);project.sourceBlob=file;project.sourceName=file.name;project.sourceType=info.sourceType;$('modelNameBadge').textContent=file.name;$('polyCountBadge').textContent=`${info.triangleCount.toLocaleString()} tris`;$('viewportDropHint').classList.add('hidden');$('loadMtlButton').classList.toggle('hidden',info.sourceType!=='obj');refreshScene(info);if(!info.hasUV)showNoUvModal();else await loadEmbeddedTexture(info);markDirty();status('Model ready');}catch(e){console.error(e);toast(e.message||'Could not load model','bad');status('Load failed');}}

function showNoUvModal(){modal(`<h2>No UV map found</h2><p>This model has no usable UV coordinates. We can automatically unwrap the model, but accuracy is not guaranteed. It may look good or it may look very bad depending on the mesh.</p><div class="warning-box">Auto UV is experimental. Keep the original model safe.</div><div class="modal-actions"><button id="otherModel" class="ghost-button">Load another model</button><button id="autoUv" class="primary-button">Auto UV and load texture</button></div>`);$('otherModel').onclick=()=>{closeModal();modelInput.click();};$('autoUv').onclick=()=>{const n=viewer.autoUnwrap();closeModal();refreshScene(viewer.describeModel());toast(`Auto UV created for ${n} mesh(es)`,'good');textureInput.click();};}

async function loadEmbeddedTexture(info){if(!info.textureMaps.length){$('textureMapSelect').classList.add('hidden');return;}const select=$('textureMapSelect');select.innerHTML='';for(const m of info.textureMaps){const o=document.createElement('option');o.value=m.key;o.textContent=m.label;select.append(o);}select.classList.toggle('hidden',info.textureMaps.length<2);activeMap=info.textureMaps[0].key;select.value=activeMap;const c=await viewer.textureToCanvas(info.textureMaps[0].texture);if(c){await tex.loadImageSource(c);mapDocs.set(`${activeMap}:1001`,c);$('textureEmptyState').classList.add('hidden');updateTextureMeta();viewer.applyCanvasToMap(tex.composite(),activeMap);}refreshUdims();}

async function loadTextureFiles(files,apply=true){if(!files?.length)return;for(const file of files){try{if(file.size>128*1024*1024)toast('Large texture detected. Performance may be affected.');const name=file.name.toLowerCase(),udimMatch=name.match(/(?:^|[._-])(1\d{3})(?:[._-]|$)/),udim=udimMatch?Number(udimMatch[1]):1001;const texture=await viewer.loadTextureFile(file);const c=await viewer.textureToCanvas(texture);if(!c)throw new Error(`Could not decode ${file.name}`);mapDocs.set(`${activeMap}:${udim}`,c);if(udim===activeUdim||files.length===1){activeUdim=udim;await tex.loadImageSource(c);tex.activeTile=udim;}if(apply&&udim===1001)viewer.applyTextureObject(texture,activeMap);project.textureBlob=file;project.textureName=file.name;$('textureEmptyState').classList.add('hidden');}catch(e){toast(e.message||`Could not load ${file.name}`,'bad');}}refreshUdims();updateTextureMeta();markDirty();}

function refreshUdims(){const set=new Set(viewer.getUDIMTiles());for(const k of mapDocs.keys()){const [map,u]=k.split(':');if(map===activeMap)set.add(Number(u));}const values=[...set].sort((a,b)=>a-b),s=$('udimSelect');s.innerHTML='';for(const u of values){const o=document.createElement('option');o.value=u;o.textContent=String(u);s.append(o);}s.value=String(activeUdim);s.classList.toggle('hidden',values.length<=1);}
function updateTextureMeta(){const c=tex.composite();$('textureResolutionLabel').textContent=`${c.width} × ${c.height}`;$('textureZoomLabel').textContent=`${Math.round(tex.zoom*100)}%`;}

function refreshScene(info){const meshList=$('meshList');meshList.innerHTML='';info.meshes.forEach((m,i)=>{const row=document.createElement('div');row.className='mesh-row';row.innerHTML=`<input type="checkbox" checked><span>${m.name||`Mesh ${i+1}`}</span>`;row.querySelector('input').onchange=e=>viewer.setMeshVisible(m,e.target.checked);meshList.append(row);});const uv=$('uvSetSelect');uv.innerHTML='';(info.uvSets.length?info.uvSets:['uv']).forEach((n,i)=>{const o=document.createElement('option');o.value=n;o.textContent=`UV${i}`;uv.append(o);});$('animationSection').classList.toggle('hidden',!info.animations.length);$('animationSelect').innerHTML='';info.animations.forEach((a,i)=>{const o=document.createElement('option');o.value=i;o.textContent=a.name||`Animation ${i+1}`;$('animationSelect').append(o);});refreshTextureMaps();refreshUdims();buildUvTriangles();}
function refreshTextureMaps(){const maps=viewer.getAvailableTextureMaps(),s=$('textureMapSelect');s.innerHTML='';maps.forEach(m=>{const o=document.createElement('option');o.value=m.key;o.textContent=m.label;s.append(o);});if(!maps.find(m=>m.key===activeMap)&&maps[0])activeMap=maps[0].key;s.value=activeMap;s.classList.toggle('hidden',maps.length<=1);}
function buildUvTriangles(){const arr=[];for(const mesh of viewer.meshes){const a=mesh.geometry.getAttribute(viewer.uvSetName)||mesh.geometry.getAttribute('uv');if(!a)continue;const g=mesh.geometry,n=Math.floor((g.index?.count||g.getAttribute('position').count)/3);for(let f=0;f<n;f++){const vi=g.index?[g.index.getX(f*3),g.index.getX(f*3+1),g.index.getX(f*3+2)]:[f*3,f*3+1,f*3+2],uvs=vi.map(i=>({x:a.getX(i),y:a.getY(i)})),u=(uvs[0].x+uvs[1].x+uvs[2].x)/3,v=(uvs[0].y+uvs[1].y+uvs[2].y)/3;arr.push({mesh,faceIndex:f,uvs,udim:1001+Math.floor(u)+Math.floor(v)*10});if(arr.length>100000)break;}if(arr.length>100000)break;}tex.setUVTriangles(arr);}

function setTool(tool){viewer.setTool(tool);tex.setTool(tool==='paint3d'?'brush':tool);document.querySelectorAll('.tool-button').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));const names={select:'Select / Inspect',brush:'Brush',eraser:'Eraser',paint3d:'Paint on Model',eyedropper:'Eyedropper',fill:'Fill',line:'Line',rect:'Rectangle',ellipse:'Ellipse',lasso:'Lasso',move:'Move / Transform'};$('activeToolName').textContent=names[tool]||tool;}
document.querySelectorAll('.tool-button').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));

viewer.onFaceSelect=info=>{tex.setSelectedUV(info);activeUdim=info.udim;$('udimSelect').value=String(activeUdim);};viewer.onFaceHover=info=>tex.setHoverUV(info);viewer.onPaintUV=e=>{if(e.end){tex.end3DStroke();return;}tex.paintUV(e.u,e.v,e.pressure,e.start);};viewer.onModelChanged=info=>refreshScene(info);
tex.onUVSelect=(u,v)=>viewer.selectFaceByUV(u,v);tex.onUVHover=(u,v)=>viewer.hoverFaceByUV(u,v);tex.onCoordinates=(u,v)=>$('uvCoordinateLabel').textContent=`U: ${u.toFixed(3)} V: ${v.toFixed(3)}`;tex.onZoom=z=>$('textureZoomLabel').textContent=`${Math.round(z*100)}%`;tex.onHistory=()=>renderHistory();tex.onChange=e=>{if(e.type==='color'){$('colorInput').value=e.color;$('colorHexInput').value=e.color;return;}if(e.canvas&&activeUdim===1001)viewer.applyCanvasToMap(e.canvas,activeMap);markDirty();renderLayers();renderHistory();};

function renderLayers(){const list=$('layerList');list.innerHTML='';[...tex.layers].reverse().forEach(l=>{const r=document.createElement('div');r.className=`layer-row ${l.id===tex.activeLayerId?'active':''}`;r.innerHTML=`<button class="vis">${l.visible?'●':'○'}</button><div class="layer-preview"></div><span class="grow"></span><button class="lock">${l.locked?'🔒':'○'}</button>`;r.querySelector('.grow').textContent=l.name;r.onclick=()=>{tex.setLayer(l.id);renderLayers();syncLayerControls();};r.querySelector('.vis').onclick=e=>{e.stopPropagation();tex.setLayerVisible(l.id,!l.visible);renderLayers();};r.querySelector('.lock').onclick=e=>{e.stopPropagation();tex.setLayerLocked(l.id,!l.locked);renderLayers();};list.append(r);});syncLayerControls();}
function syncLayerControls(){const l=tex.activeLayer;if(!l)return;$('blendModeSelect').value=l.blend;$('layerOpacityInput').value=Math.round(l.opacity*100);$('layerOpacityValue').textContent=`${Math.round(l.opacity*100)}%`;}
function renderHistory(){const h=$('historyList');h.innerHTML='';tex.history.slice(-50).forEach(x=>{const e=document.createElement('div');e.className='history-item';e.innerHTML=`<strong></strong><span></span>`;e.querySelector('strong').textContent=x.label;e.querySelector('span').textContent=new Date(x.time).toLocaleTimeString();h.append(e);});$('historyCountLabel').textContent=`${tex.history.length} actions`;const v=$('versionList');v.innerHTML='';tex.versions.forEach(x=>{const e=document.createElement('div');e.className='version-item';e.innerHTML=`<div><strong></strong><br><small></small></div><button>Apply</button>`;e.querySelector('strong').textContent=x.name;e.querySelector('small').textContent=new Date(x.time).toLocaleString();e.querySelector('button').onclick=()=>tex.applyVersion(x.id);v.append(e);});}

function updateBrush(){tex.setBrush({color:$('colorInput').value,size:Number($('brushSizeInput').value),opacity:Number($('brushOpacityInput').value)/100,hardness:Number($('brushHardnessInput').value)/100,stabilization:Number($('brushStabilizationInput').value)/100,pressureSize:$('pressureSizeInput').checked,pressureOpacity:$('pressureOpacityInput').checked});$('brushSizeValue').textContent=`${$('brushSizeInput').value} px`;$('brushOpacityValue').textContent=`${$('brushOpacityInput').value}%`;$('brushHardnessValue').textContent=`${$('brushHardnessInput').value}%`;$('brushStabilizationValue').textContent=`${$('brushStabilizationInput').value}%`;}
['brushSizeInput','brushOpacityInput','brushHardnessInput','brushStabilizationInput','pressureSizeInput','pressureOpacityInput'].forEach(id=>$(id).addEventListener('input',updateBrush));$('colorInput').oninput=()=>{$('colorHexInput').value=$('colorInput').value;updateBrush();};$('colorHexInput').onchange=()=>{if(/^#[0-9a-f]{6}$/i.test($('colorHexInput').value))$('colorInput').value=$('colorHexInput').value;updateBrush();};

$('addLayerButton').onclick=()=>{tex.addLayer();renderLayers();};$('duplicateLayerButton').onclick=()=>{tex.duplicateLayer();renderLayers();};$('deleteLayerButton').onclick=()=>{tex.deleteLayer();renderLayers();};$('blendModeSelect').onchange=e=>tex.setLayerBlend(e.target.value);$('layerOpacityInput').oninput=e=>{tex.setLayerOpacity(Number(e.target.value)/100);syncLayerControls();};$('undoButton').onclick=()=>tex.undo();$('redoButton').onclick=()=>tex.redo();
$('saveVersionButton').onclick=()=>{tex.addVersion();renderHistory();markDirty();};

$('newProjectButton').onclick=()=>modelInput.click();$('heroUploadButton').onclick=()=>modelInput.click();$('loadModelButton').onclick=()=>modelInput.click();modelInput.onchange=()=>{const f=modelInput.files[0];if(f){if(!project)newProjectWithFile(f);else loadModel(f);}modelInput.value='';};$('loadTextureButton').onclick=()=>textureInput.click();$('textureEmptyUpload').onclick=()=>textureInput.click();textureInput.onchange=()=>{loadTextureFiles([...textureInput.files]);textureInput.value='';};$('loadMtlButton').onclick=()=>mtlInput.click();mtlInput.onchange=async()=>{if(mtlInput.files[0]){const info=await viewer.loadMtlFile(mtlInput.files[0]);refreshScene(info);markDirty();}mtlInput.value='';};
$('backDashboardButton').onclick=async()=>{if(dirty)await saveCurrentProject();showDashboard();};$('languageButton').onclick=()=>toggleLanguage();$('projectNameInput').oninput=markDirty;
$('gridToggle').onchange=e=>viewer.setGridVisible(e.target.checked);$('wireframeToggle').onchange=e=>viewer.setWireframe(e.target.checked);$('lightingToggle').onchange=e=>viewer.setLighting(e.target.checked);$('resetCameraButton').onclick=()=>viewer.fitCamera();$('fullscreenButton').onclick=()=>document.fullscreenElement?document.exitFullscreen():$('viewportWrap').requestFullscreen();
$('playAnimationButton').onclick=()=>viewer.playAnimation(Number($('animationSelect').value||0));$('pauseAnimationButton').onclick=()=>viewer.pauseAnimation();$('stopAnimationButton').onclick=()=>viewer.stopAnimation();$('uvSetSelect').onchange=e=>{viewer.setUVSet(e.target.value);buildUvTriangles();};
$('fitTextureButton').onclick=()=>tex.fit();$('toggleUvPanelButton').onclick=()=>$('uvPanel').classList.toggle('hidden');$('closeUvButton').onclick=()=>$('uvPanel').classList.add('hidden');$('maximizeUvButton').onclick=()=>{$('uvPanel').classList.toggle('maximized');setTimeout(()=>tex.resize(),20);};
$('historyPanelButton').onclick=()=>$('historyDrawer').classList.toggle('hidden');$('closeHistoryButton').onclick=()=>$('historyDrawer').classList.add('hidden');
$('compareButton').onclick=$('compareToolButton').onclick=()=>{compare=!compare;$('uvPanel').classList.toggle('compare-mode',compare);};
$('textureMapSelect').onchange=async e=>{activeMap=e.target.value;const key=`${activeMap}:${activeUdim}`,saved=mapDocs.get(key);if(saved)await tex.loadImageSource(saved);else{const entry=viewer.getAvailableTextureMaps().find(m=>m.key===activeMap),c=entry?await viewer.textureToCanvas(entry.texture):null;if(c)await tex.loadImageSource(c);}refreshUdims();updateTextureMeta();};
$('udimSelect').onchange=async e=>{activeUdim=Number(e.target.value);tex.activeTile=activeUdim;const c=mapDocs.get(`${activeMap}:${activeUdim}`);if(c)await tex.loadImageSource(c);tex.render();};

$('exportTextureButton').onclick=async()=>{const b=await tex.toBlob('image/png');downloadBlob(b,`${fileBase(project?.name||'texture')}-${activeMap}-${activeUdim}.png`);};$('exportModelButton').onclick=()=>$('exportMenu').classList.toggle('hidden');$('exportGlbButton').onclick=async()=>{try{status('Exporting GLB');const b=await exportGLB(viewer.modelRoot,viewer.animations);downloadBlob(b,`${fileBase(project?.name)}.glb`);toast('GLB exported','good');}catch(e){toast(e.message,'bad');}};$('exportFbxButton').onclick=()=>modal(`<h2>Experimental FBX export</h2><p>FBX export may lose rigs, animation, materials or texture details. GLB is the safe option.</p><div class="modal-actions"><button id="cancelFbx" class="ghost-button">Cancel</button><button id="confirmFbxExport" class="primary-button">Export FBX</button></div>`);
document.addEventListener('click',e=>{if(e.target?.id==='cancelFbx')closeModal();if(e.target?.id==='confirmFbxExport'){try{downloadBlob(exportFBXExperimental(viewer.modelRoot),`${fileBase(project?.name)}.fbx`);closeModal();toast('FBX exported','good');}catch(err){toast(err.message,'bad');}}});

$('trashButton').onclick=async()=>{const items=await listProjects({trash:true});modal(`<h2>Trash</h2><p>Deleted projects can be recovered for 30 days. They are permanently removed when the app is opened after that period.</p><div id="trashRows" class="trash-list"></div><div class="modal-actions"><button id="closeTrash" class="ghost-button">Close</button></div>`);const box=$('trashRows');for(const p of items){const r=document.createElement('div');r.className='trash-row';r.innerHTML=`<div><strong></strong><span></span></div><span class="button-row"><button class="small-button restore">Restore</button><button class="small-button del">Delete forever</button></span>`;r.querySelector('strong').textContent=p.name;r.querySelector('span').textContent=new Date(p.deletedAt).toLocaleString();r.querySelector('.restore').onclick=async()=>{await restoreProject(p.id);closeModal();renderProjects();};r.querySelector('.del').onclick=async()=>{await deleteProjectForever(p.id);r.remove();};box.append(r);}if(!items.length)box.innerHTML='<div class="muted">Trash is empty.</div>';$('closeTrash').onclick=closeModal;};
$('settingsButton').onclick=async()=>{const est=await estimateStorage();modal(`<h2>Settings</h2><p>UVMap - Online stores projects only in this browser. Clearing site data removes local projects.</p><div class="warning-box">Storage used: ${est?formatBytes(est.usage):'Unknown'} of ${est?formatBytes(est.quota):'Unknown'}</div><div class="modal-actions"><button id="persistStorage" class="ghost-button">Request persistent storage</button><button id="closeSettings" class="primary-button">Close</button></div>`);$('persistStorage').onclick=async()=>toast(await requestPersistentStorage()?'Persistent storage granted':'Browser did not grant persistent storage');$('closeSettings').onclick=closeModal;};

for(const tab of document.querySelectorAll('.panel-tab'))tab.onclick=()=>{document.querySelectorAll('.panel-tab').forEach(x=>x.classList.toggle('active',x===tab));['tool','scene','layers'].forEach(n=>$(`${n}Panel`).classList.toggle('hidden',tab.dataset.panel!==n));};
$('viewportWrap').addEventListener('dragover',e=>{e.preventDefault();$('viewportWrap').classList.add('dragging');});$('viewportWrap').addEventListener('dragleave',()=>$('viewportWrap').classList.remove('dragging'));$('viewportWrap').addEventListener('drop',e=>{e.preventDefault();$('viewportWrap').classList.remove('dragging');const f=[...e.dataTransfer.files].find(x=>/\.(glb|gltf|fbx|obj)$/i.test(x.name));if(f){if(!project)newProjectWithFile(f);else loadModel(f);}});

window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(document.activeElement?.tagName))return;const k=e.key.toLowerCase(),map={v:'select',b:'brush',e:'eraser',p:'paint3d',i:'eyedropper',g:'fill',l:'line',r:'rect',o:'ellipse',m:'move'};if(map[k])setTool(map[k]);if((e.ctrlKey||e.metaKey)&&k==='z'){e.preventDefault();e.shiftKey?tex.redo():tex.undo();}if(e.key==='Home')viewer.fitCamera();});

async function mobileWarning(){if(matchMedia('(max-width: 900px)').matches&&!sessionStorage.getItem('uvmap-mobile-warning')){sessionStorage.setItem('uvmap-mobile-warning','1');modal(`<h2>Desktop first application</h2><p>UVMap - Online is designed primarily for desktop use. Mobile editing is supported experimentally. Expect layout, performance and input issues.</p><div class="modal-actions"><button id="mobileOk" class="primary-button">Continue</button></div>`);$('mobileOk').onclick=closeModal;}}

applyTranslations();updateBrush();renderLayers();renderHistory();renderProjects();mobileWarning();
