import * as THREE from 'three';
import { GLTFExporter } from 'three/addons/exporters/GLTFExporter.js';

export async function exportGLB(root, animations = []) {
  if (!root) throw new Error('No model is loaded.');
  const exporter = new GLTFExporter();
  return new Promise((resolve, reject) => {
    exporter.parse(
      root,
      result => {
        if (result instanceof ArrayBuffer) resolve(new Blob([result], { type: 'model/gltf-binary' }));
        else resolve(new Blob([JSON.stringify(result)], { type: 'model/gltf+json' }));
      },
      reject,
      {
        binary: true,
        animations,
        onlyVisible: true,
        truncateDrawRange: true,
        maxTextureSize: Infinity,
      }
    );
  });
}

function sanitizeName(name) {
  return String(name || 'Mesh').replace(/[^a-zA-Z0-9_.-]/g, '_');
}

function fbxArray(name, values, decimals = 8) {
  const formatted = values.map(value => Number(value).toFixed(decimals).replace(/\.0+$/, '').replace(/(\.\d*?)0+$/, '$1'));
  return `${name}: *${values.length} {\n\t\ta: ${formatted.join(',')}\n\t}`;
}

function meshToFbxParts(mesh, geometryId, modelId) {
  const geometry = mesh.geometry;
  const position = geometry.getAttribute('position');
  if (!position) return null;
  const normal = geometry.getAttribute('normal');
  const uv = geometry.getAttribute('uv');
  const world = mesh.matrixWorld.clone();
  const normalMatrix = new THREE.Matrix3().getNormalMatrix(world);
  const vertices = [];
  for (let i = 0; i < position.count; i++) {
    const v = new THREE.Vector3().fromBufferAttribute(position, i).applyMatrix4(world);
    vertices.push(v.x, v.y, v.z);
  }

  const polyIndices = [];
  const polygonVertexNormals = [];
  const uvValues = [];
  const uvIndices = [];
  const triangleCount = geometry.index ? geometry.index.count / 3 : position.count / 3;
  let uvCounter = 0;

  for (let face = 0; face < triangleCount; face++) {
    const ids = geometry.index
      ? [geometry.index.getX(face * 3), geometry.index.getX(face * 3 + 1), geometry.index.getX(face * 3 + 2)]
      : [face * 3, face * 3 + 1, face * 3 + 2];
    ids.forEach((index, corner) => {
      polyIndices.push(corner === 2 ? -index - 1 : index);
      if (normal) {
        const n = new THREE.Vector3().fromBufferAttribute(normal, index).applyMatrix3(normalMatrix).normalize();
        polygonVertexNormals.push(n.x, n.y, n.z);
      }
      if (uv) {
        uvValues.push(uv.getX(index), uv.getY(index));
        uvIndices.push(uvCounter++);
      }
    });
  }

  const name = sanitizeName(mesh.name || `Mesh_${geometryId}`);
  const normalLayer = normal ? `
\tLayerElementNormal: 0 {
\t\tVersion: 101
\t\tName: ""
\t\tMappingInformationType: "ByPolygonVertex"
\t\tReferenceInformationType: "Direct"
\t\t${fbxArray('Normals', polygonVertexNormals)}
\t}` : '';
  const uvLayer = uv ? `
\tLayerElementUV: 0 {
\t\tVersion: 101
\t\tName: "UVChannel_1"
\t\tMappingInformationType: "ByPolygonVertex"
\t\tReferenceInformationType: "IndexToDirect"
\t\t${fbxArray('UV', uvValues)}
\t\t${fbxArray('UVIndex', uvIndices, 0)}
\t}` : '';
  const layerEntries = `${normal ? '\n\t\tLayerElement:  { Type: "LayerElementNormal" TypedIndex: 0 }' : ''}${uv ? '\n\t\tLayerElement:  { Type: "LayerElementUV" TypedIndex: 0 }' : ''}`;

  const object = `Geometry: ${geometryId}, "Geometry::${name}", "Mesh" {
\tGeometryVersion: 124
\t${fbxArray('Vertices', vertices)}
\t${fbxArray('PolygonVertexIndex', polyIndices, 0)}${normalLayer}${uvLayer}
\tLayer: 0 {
\t\tVersion: 100${layerEntries}
\t}
}
Model: ${modelId}, "Model::${name}", "Mesh" {
\tVersion: 232
\tProperties70:  {
\t\tP: "Lcl Translation", "Lcl Translation", "", "A",0,0,0
\t\tP: "Lcl Rotation", "Lcl Rotation", "", "A",0,0,0
\t\tP: "Lcl Scaling", "Lcl Scaling", "", "A",1,1,1
\t}
\tShading: T
\tCulling: "CullingOff"
}`;

  return { object, connections: `C: "OO",${geometryId},${modelId}\n\tC: "OO",${modelId},0` };
}

export function exportFBXExperimental(root) {
  if (!root) throw new Error('No model is loaded.');
  root.updateMatrixWorld(true);
  const parts = [];
  let idSeed = 100000;
  let meshCount = 0;
  root.traverse(object => {
    if (!object.isMesh || !object.visible) return;
    const geometryId = idSeed++;
    const modelId = idSeed++;
    const part = meshToFbxParts(object, geometryId, modelId);
    if (part) {
      parts.push(part);
      meshCount++;
    }
  });
  if (!meshCount) throw new Error('No visible mesh could be exported.');

  const objects = parts.map(part => part.object).join('\n');
  const connections = parts.map(part => part.connections).join('\n\t');
  const text = `; FBX 7.4.0 project file
; Generated by UVMap - Online
FBXHeaderExtension:  {
\tFBXHeaderVersion: 1003
\tFBXVersion: 7400
\tCreator: "UVMap - Online"
}
GlobalSettings:  {
\tVersion: 1000
\tProperties70:  {
\t\tP: "UpAxis", "int", "Integer", "",1
\t\tP: "UpAxisSign", "int", "Integer", "",1
\t\tP: "FrontAxis", "int", "Integer", "",2
\t\tP: "FrontAxisSign", "int", "Integer", "",-1
\t\tP: "CoordAxis", "int", "Integer", "",0
\t\tP: "CoordAxisSign", "int", "Integer", "",1
\t\tP: "UnitScaleFactor", "double", "Number", "",1
\t}
}
Definitions:  {
\tVersion: 100
\tCount: ${meshCount * 2}
\tObjectType: "Geometry" { Count: ${meshCount} }
\tObjectType: "Model" { Count: ${meshCount} }
}
Objects:  {
${objects.split('\n').map(line => `\t${line}`).join('\n')}
}
Connections:  {
\t${connections}
}
`;
  return new Blob([text], { type: 'application/octet-stream' });
}

export function downloadBlob(blob, filename) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}
