import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { FBXLoader } from 'three/addons/loaders/FBXLoader.js';
import { OBJLoader } from 'three/addons/loaders/OBJLoader.js';
import { MTLLoader } from 'three/addons/loaders/MTLLoader.js';
import { TGALoader } from 'three/addons/loaders/TGALoader.js';
import { DDSLoader } from 'three/addons/loaders/DDSLoader.js';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';

const MAPS = [['map','Base Color'],['normalMap','Normal'],['roughnessMap','Roughness'],['metalnessMap','Metallic'],['aoMap','Ambient Occlusion'],['emissiveMap','Emissive'],['specularMap','Specular'],['specularColorMap','Specular Color'],['alphaMap','Alpha'],['bumpMap','Bump'],['displacementMap','Displacement'],['lightMap','Light']];
const mats = mesh => Array.isArray(mesh.material) ? mesh.material : [mesh.material];
const ids = (g,f) => g.index ? [g.index.getX(f*3),g.index.getX(f*3+1),g.index.getX(f*3+2)] : [f*3,f*3+1,f*3+2];
const uvAttr = (g,n='uv') => g.getAttribute(n) || g.getAttribute('uv');
function inside(p,a,b,c){const v0={x:c.x-a.x,y:c.y-a.y},v1={x:b.x-a.x,y:b.y-a.y},v2={x:p.x-a.x,y:p.y-a.y};const d00=v0.x*v0.x+v0.y*v0.y,d01=v0.x*v1.x+v0.y*v1.y,d02=v0.x*v2.x+v0.y*v2.y,d11=v1.x*v1.x+v1.y*v1.y,d12=v1.x*v2.x+v1.y*v2.y,den=d00*d11-d01*d01;if(Math.abs(den)<1e-10)return false;const u=(d11*d02-d01*d12)/den,v=(d00*d12-d01*d02)/den;return u>=0&&v>=0&&u+v<=1;}

export class ModelViewer {
  constructor(canvas){
    this.canvas=canvas;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x111419);this.camera=new THREE.PerspectiveCamera(45,1,.01,10000);this.camera.position.set(2.5,1.8,3.5);
    this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.renderer.toneMapping=THREE.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.1;
    this.pmrem=new THREE.PMREMGenerator(this.renderer);this.environment=this.pmrem.fromScene(new RoomEnvironment(),0.04).texture;this.scene.environment=this.environment;
    this.controls=new OrbitControls(this.camera,canvas);this.controls.enableDamping=true;this.controls.screenSpacePanning=true;this.controls.mouseButtons.LEFT=null;this.controls.mouseButtons.MIDDLE=THREE.MOUSE.ROTATE;this.controls.mouseButtons.RIGHT=THREE.MOUSE.PAN;
    this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.clock=new THREE.Clock();this.modelRoot=null;this.meshes=[];this.animations=[];this.mixer=null;this.action=null;this.uvSetName='uv';this.tool='select';this.sourceFile=null;this.sourceType='';this.objText='';this.painting=false;
    this.grid=new THREE.GridHelper(20,20,0x474e5a,0x262b33);this.scene.add(this.grid);this.ambient=new THREE.HemisphereLight(0xdce8ff,0x1b1d21,1.6);this.key=new THREE.DirectionalLight(0xffffff,2.5);this.key.position.set(4,7,5);this.scene.add(this.ambient,this.key);
    this.selectedLine=this.line(0xff7a1a);this.hoverLine=this.line(0x6ed7ff);this.scene.add(this.selectedLine,this.hoverLine);
    this.onFaceSelect=null;this.onFaceHover=null;this.onPaintUV=null;this.onModelChanged=null;
    canvas.addEventListener('pointerdown',e=>this.down(e));canvas.addEventListener('pointermove',e=>this.move(e));window.addEventListener('pointerup',()=>this.up());canvas.addEventListener('contextmenu',e=>e.preventDefault());new ResizeObserver(()=>this.resize()).observe(canvas.parentElement);this.resize();this.renderer.setAnimationLoop(()=>this.render());
  }
  line(color){const l=new THREE.LineLoop(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color,depthTest:false}));l.visible=false;l.renderOrder=999;return l;}
  resize(){const p=this.canvas.parentElement,w=Math.max(1,p.clientWidth),h=Math.max(1,p.clientHeight);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h,false);}
  render(){if(this.mixer)this.mixer.update(Math.min(this.clock.getDelta(),.05));this.controls.update();this.renderer.render(this.scene,this.camera);}
  setTool(t){this.tool=t;if(t!=='paint3d'){this.painting=false;this.controls.enabled=true;}}
  ray(e){if(!this.modelRoot)return null;const r=this.canvas.getBoundingClientRect();this.pointer.set((e.clientX-r.left)/r.width*2-1,-((e.clientY-r.top)/r.height*2-1));this.raycaster.setFromCamera(this.pointer,this.camera);return this.raycaster.intersectObjects(this.meshes.filter(m=>m.visible),false).find(x=>Number.isInteger(x.faceIndex))||null;}
  down(e){if(e.button!==0)return;if(this.tool==='paint3d'){this.painting=true;this.controls.enabled=false;const h=this.ray(e);if(h?.uv)this.onPaintUV?.({u:h.uv.x,v:h.uv.y,pressure:e.pressure||1,start:true});return;}if(this.tool!=='select')return;const h=this.ray(e);if(h)this.select(this.faceInfo(h.object,h.faceIndex));}
  move(e){if(this.tool==='paint3d'&&this.painting){const h=this.ray(e);if(h?.uv)this.onPaintUV?.({u:h.uv.x,v:h.uv.y,pressure:e.pressure||1});return;}if(e.buttons)return;const h=this.ray(e);if(!h){this.hoverLine.visible=false;this.onFaceHover?.(null);return;}const i=this.faceInfo(h.object,h.faceIndex);if(i){this.highlight(this.hoverLine,i);this.onFaceHover?.(i);}}
  up(){if(this.painting){this.painting=false;this.controls.enabled=true;this.onPaintUV?.({end:true});}}
  faceInfo(mesh,faceIndex){const a=uvAttr(mesh.geometry,this.uvSetName);if(!a)return null;const uvs=ids(mesh.geometry,faceIndex).map(i=>new THREE.Vector2(a.getX(i),a.getY(i)));const u=(uvs[0].x+uvs[1].x+uvs[2].x)/3,v=(uvs[0].y+uvs[1].y+uvs[2].y)/3;return{mesh,faceIndex,uvs,udim:1001+Math.floor(u)+Math.floor(v)*10};}
  highlight(line,info){if(!info){line.visible=false;return;}const p=info.mesh.geometry.getAttribute('position'),pts=ids(info.mesh.geometry,info.faceIndex).map(i=>info.mesh.localToWorld(new THREE.Vector3().fromBufferAttribute(p,i)));line.geometry.dispose();line.geometry=new THREE.BufferGeometry().setFromPoints(pts);line.visible=true;}
  select(info){if(!info)return;this.selectedFace=info;this.highlight(this.selectedLine,info);this.onFaceSelect?.(info);}
  findFaceByUV(u,v){for(const mesh of this.meshes){const a=uvAttr(mesh.geometry,this.uvSetName);if(!a)continue;const g=mesh.geometry,n=(g.index?g.index.count:g.getAttribute('position').count)/3;for(let f=0;f<n;f++){const t=ids(g,f).map(i=>({x:a.getX(i),y:a.getY(i)}));if(inside({x:u,y:v},t[0],t[1],t[2]))return this.faceInfo(mesh,f);}}return null;}
  selectFaceByUV(u,v){const i=this.findFaceByUV(u,v);if(i)this.select(i);return i;}
  hoverFaceByUV(u,v){const i=this.findFaceByUV(u,v);this.highlight(this.hoverLine,i);return i;}
  async loadFile(file){this.sourceFile=file;this.sourceType=file.name.split('.').pop().toLowerCase();let root,animations=[];if(['glb','gltf'].includes(this.sourceType)){const l=new GLTFLoader(),data=this.sourceType==='gltf'?await file.text():await file.arrayBuffer(),g=await new Promise((ok,no)=>l.parse(data,'',ok,no));root=g.scene;animations=g.animations||[];}else if(this.sourceType==='fbx'){root=new FBXLoader().parse(await file.arrayBuffer(),'');animations=root.animations||[];}else if(this.sourceType==='obj'){this.objText=await file.text();root=new OBJLoader().parse(this.objText);}else throw new Error('Unsupported model format');this.setModel(root,animations);return this.describeModel();}
  async loadMtlFile(file){if(!this.objText)throw new Error('Load OBJ first');const m=new MTLLoader().parse(await file.text(),'');m.preload();const l=new OBJLoader();l.setMaterials(m);this.setModel(l.parse(this.objText),[]);return this.describeModel();}
  setModel(root,animations=[]){if(this.modelRoot)this.scene.remove(this.modelRoot);this.modelRoot=root;this.scene.add(root);this.meshes=[];root.traverse(o=>{if(o.isMesh)this.meshes.push(o);});this.animations=animations;this.mixer=animations.length?new THREE.AnimationMixer(root):null;this.action=null;this.fitCamera();this.onModelChanged?.(this.describeModel());}
  fitCamera(){if(!this.modelRoot)return;const b=new THREE.Box3().setFromObject(this.modelRoot),s=b.getSize(new THREE.Vector3()),c=b.getCenter(new THREE.Vector3()),m=Math.max(s.x,s.y,s.z,.01),d=m/(2*Math.tan(THREE.MathUtils.degToRad(this.camera.fov/2)))*1.4;this.controls.target.copy(c);this.camera.position.copy(c).add(new THREE.Vector3(d*.7,d*.45,d));this.camera.near=Math.max(.001,m/1000);this.camera.far=Math.max(100,m*1000);this.camera.updateProjectionMatrix();}
  getUVSetNames(){const s=new Set();this.meshes.forEach(m=>Object.keys(m.geometry.attributes).forEach(n=>{if(/^uv\d*$/.test(n))s.add(n);}));return[...s];}
  setUVSet(n){this.uvSetName=n||'uv';}
  getUDIMTiles(){const s=new Set([1001]);this.meshes.forEach(m=>{const a=uvAttr(m.geometry,this.uvSetName);if(a)for(let i=0;i<a.count;i++)s.add(1001+Math.floor(a.getX(i))+Math.floor(a.getY(i))*10);});return[...s].sort((a,b)=>a-b);}
  getAvailableTextureMaps(){const f=new Map();this.meshes.forEach(mesh=>mats(mesh).forEach(mat=>MAPS.forEach(([key,label])=>{if(mat?.[key]?.isTexture&&!f.has(key))f.set(key,{key,label,texture:mat[key]});})));return[...f.values()];}
  describeModel(){const missing=this.meshes.filter(m=>!m.geometry.getAttribute('uv')),tris=this.meshes.reduce((n,m)=>n+Math.floor((m.geometry.index?.count||m.geometry.getAttribute('position')?.count||0)/3),0);return{hasUV:missing.length<this.meshes.length,allMeshesHaveUV:missing.length===0,missingUVMeshes:missing,hasTextures:this.getAvailableTextureMaps().length>0,textureMaps:this.getAvailableTextureMaps(),uvSets:this.getUVSetNames(),triangleCount:tris,meshes:this.meshes,animations:this.animations,sourceType:this.sourceType};}
  async textureToCanvas(texture){const src=texture?.image||texture?.source?.data;if(!src)return null;const w=src.width||src.naturalWidth,h=src.height||src.naturalHeight;if(!w||!h)return null;const c=document.createElement('canvas');c.width=w;c.height=h;const ctx=c.getContext('2d',{willReadFrequently:true});try{if(src.data&&src.data.length>=w*h*4){const data=src.data instanceof Uint8ClampedArray?src.data:new Uint8ClampedArray(src.data.buffer,src.data.byteOffset,Math.min(src.data.byteLength,w*h*4));ctx.putImageData(new ImageData(data,w,h),0,0);}else ctx.drawImage(src,0,0,w,h);return c;}catch{return null;}}
  configureTexture(texture,key='map'){texture.flipY=false;texture.colorSpace=['map','emissiveMap','specularColorMap'].includes(key)?THREE.SRGBColorSpace:THREE.NoColorSpace;texture.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());texture.needsUpdate=true;return texture;}
  prepareMaterial(mesh,mat,key='map'){if(key==='map'){mat.color?.setRGB?.(1,1,1);const colors=mesh.geometry.getAttribute('color');if(mat.vertexColors&&colors){let max=0,step=Math.max(1,Math.floor(colors.count/512));for(let i=0;i<colors.count;i+=step){max=Math.max(max,colors.getX(i),colors.getY(i),colors.getZ(i));if(max>.01)break;}if(max<=.01)mat.vertexColors=false;}}if('envMapIntensity'in mat&&(!Number.isFinite(mat.envMapIntensity)||mat.envMapIntensity<=0))mat.envMapIntensity=1;mat.needsUpdate=true;}
  applyCanvasToMap(canvas,key='map'){let n=0;this.meshes.forEach(mesh=>{if(!uvAttr(mesh.geometry,this.uvSetName))return;mats(mesh).forEach(mat=>{if(!mat)return;const old=mat[key],t=this.configureTexture(new THREE.CanvasTexture(canvas),key);t.userData.uvmapOwned=true;mat[key]=t;this.prepareMaterial(mesh,mat,key);if(old?.isTexture&&old.userData?.uvmapOwned)old.dispose();n++;});});return n;}
  async loadTextureFile(file){const ext=file.name.split('.').pop().toLowerCase(),url=URL.createObjectURL(file);try{let t;if(ext==='tga')t=await new TGALoader().loadAsync(url);else if(ext==='dds')t=await new DDSLoader().loadAsync(url);else{const source=await new THREE.TextureLoader().loadAsync(url),img=source.image,w=img?.naturalWidth||img?.width,h=img?.naturalHeight||img?.height;if(w&&h){const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d').drawImage(img,0,0,w,h);t=new THREE.CanvasTexture(c);source.dispose();}else t=source;}t.flipY=false;t.needsUpdate=true;return t;}finally{URL.revokeObjectURL(url);}}
  applyTextureObject(t,key='map'){let n=0;this.meshes.forEach(mesh=>{if(!uvAttr(mesh.geometry,this.uvSetName))return;mats(mesh).forEach(mat=>{if(!mat)return;const old=mat[key],next=this.configureTexture(t.clone(),key);next.userData.uvmapOwned=true;mat[key]=next;this.prepareMaterial(mesh,mat,key);if(old?.isTexture&&old.userData?.uvmapOwned)old.dispose();n++;});});return n;}
  autoUnwrap(){let n=0;this.meshes.forEach(mesh=>{if(mesh.geometry.getAttribute('uv'))return;let g=mesh.geometry.index?mesh.geometry.toNonIndexed():mesh.geometry;if(g!==mesh.geometry)mesh.geometry=g;g.computeVertexNormals();const p=g.getAttribute('position'),b=new THREE.Box3().setFromBufferAttribute(p),s=b.getSize(new THREE.Vector3()),uv=new Float32Array(p.count*2);for(let i=0;i<p.count;i++){uv[i*2]=(p.getX(i)-b.min.x)/Math.max(s.x,1e-6);uv[i*2+1]=(p.getY(i)-b.min.y)/Math.max(s.y,1e-6);}g.setAttribute('uv',new THREE.BufferAttribute(uv,2));n++;});this.onModelChanged?.(this.describeModel());return n;}
  setMeshVisible(m,v){m.visible=v;} setWireframe(v){this.meshes.forEach(m=>mats(m).forEach(x=>{if(x&&'wireframe'in x)x.wireframe=v;}));} setGridVisible(v){this.grid.visible=v;} setLighting(v){this.ambient.visible=this.key.visible=v;this.scene.environment=v?this.environment:null;}
  playAnimation(i=0){if(!this.mixer||!this.animations[i])return;this.mixer.stopAllAction();this.action=this.mixer.clipAction(this.animations[i]);this.action.reset().play();} pauseAnimation(){if(this.action)this.action.paused=true;} stopAnimation(){this.action?.stop();}
  getScreenshotDataUrl(){try{this.renderer.render(this.scene,this.camera);return this.canvas.toDataURL('image/jpeg',.75);}catch{return null;}}
}
