function canvas(w=1024,h=1024){const c=document.createElement('canvas');c.width=w;c.height=h;return c;}
function cloneCanvas(src){const c=canvas(src.width,src.height);c.getContext('2d').drawImage(src,0,0);return c;}
function hexToRgba(hex,a=1){const n=parseInt(hex.replace('#',''),16);return `rgba(${(n>>16)&255},${(n>>8)&255},${n&255},${a})`;}

export class TextureEditor {
  constructor(textureCanvas,overlayCanvas,wrap){
    this.view=textureCanvas;this.overlay=overlayCanvas;this.wrap=wrap;this.ctx=this.view.getContext('2d');this.octx=this.overlay.getContext('2d');this.doc=canvas(1024,1024);this.layers=[];this.activeLayerId=null;this.tool='select';this.color='#ff7a1a';this.size=36;this.opacity=1;this.hardness=.8;this.stabilization=.15;this.pressureSize=true;this.pressureOpacity=false;this.zoom=1;this.panX=0;this.panY=0;this.dragging=false;this.panning=false;this.last=null;this.strokeBefore=null;this.selection=null;this.history=[];this.redoStack=[];this.versions=[];this.selectedUV=null;this.hoverUV=null;this.uvTriangles=[];this.activeTile=1001;this.onChange=null;this.onHistory=null;this.onUVSelect=null;this.onUVHover=null;this.onCoordinates=null;this.onZoom=null;this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(wrap);this.bind();this.newDocument(1024,1024);
  }
  bind(){
    this.overlay.addEventListener('pointerdown',e=>this.down(e));this.overlay.addEventListener('pointermove',e=>this.move(e));window.addEventListener('pointerup',e=>this.up(e));this.overlay.addEventListener('wheel',e=>{e.preventDefault();const f=e.deltaY<0?1.1:.9;this.zoom=Math.max(.08,Math.min(24,this.zoom*f));this.onZoom?.(this.zoom);this.render();},{passive:false});this.overlay.addEventListener('contextmenu',e=>e.preventDefault());
  }
  resize(){const r=this.wrap.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);[this.view,this.overlay].forEach(c=>{c.width=Math.max(1,Math.floor(r.width*d));c.height=Math.max(1,Math.floor(r.height*d));c.style.width=`${r.width}px`;c.style.height=`${r.height}px`;});this.render();}
  newDocument(w,h,base=null){this.doc.width=w;this.doc.height=h;this.layers=[];const baseLayer={id:crypto.randomUUID?.()||String(Date.now()),name:'Base',visible:true,locked:false,opacity:1,blend:'source-over',canvas:canvas(w,h)};if(base)baseLayer.canvas.getContext('2d').drawImage(base,0,0,w,h);this.layers.push(baseLayer);this.activeLayerId=baseLayer.id;this.history=[];this.redoStack=[];this.fit();this.render();}
  async loadImageSource(src){const w=src.width||src.naturalWidth,h=src.height||src.naturalHeight;if(!w||!h)throw new Error('Texture has no readable dimensions');const c=canvas(w,h);c.getContext('2d').drawImage(src,0,0,w,h);this.newDocument(w,h,c);this.addVersion('Original');this.changed('Load Texture',false);}
  async loadFile(file){const url=URL.createObjectURL(file);try{const img=await new Promise((ok,no)=>{const i=new Image();i.onload=()=>ok(i);i.onerror=no;i.src=url;});await this.loadImageSource(img);}finally{URL.revokeObjectURL(url);}}
  setTool(t){this.tool=t;}
  setBrush({color,size,opacity,hardness,stabilization,pressureSize,pressureOpacity}){if(color)this.color=color;if(size!=null)this.size=size;if(opacity!=null)this.opacity=opacity;if(hardness!=null)this.hardness=hardness;if(stabilization!=null)this.stabilization=stabilization;if(pressureSize!=null)this.pressureSize=pressureSize;if(pressureOpacity!=null)this.pressureOpacity=pressureOpacity;}
  get activeLayer(){return this.layers.find(l=>l.id===this.activeLayerId)||this.layers[0];}
  addLayer(name=`Layer ${this.layers.length+1}`){const l={id:crypto.randomUUID?.()||String(Date.now()+Math.random()),name,visible:true,locked:false,opacity:1,blend:'source-over',canvas:canvas(this.doc.width,this.doc.height)};this.layers.push(l);this.activeLayerId=l.id;this.changed('Add Layer');return l;}
  duplicateLayer(){const a=this.activeLayer;if(!a)return;const l={...a,id:crypto.randomUUID?.()||String(Date.now()),name:`${a.name} copy`,canvas:cloneCanvas(a.canvas)};this.layers.push(l);this.activeLayerId=l.id;this.changed('Duplicate Layer');}
  deleteLayer(){if(this.layers.length<=1)return;const i=this.layers.findIndex(l=>l.id===this.activeLayerId);if(i<0)return;this.layers.splice(i,1);this.activeLayerId=this.layers[Math.max(0,i-1)].id;this.changed('Delete Layer');}
  setLayer(id){this.activeLayerId=id;this.render();}
  setLayerVisible(id,v){const l=this.layers.find(x=>x.id===id);if(l){l.visible=v;this.changed('Layer Visibility');}}
  setLayerLocked(id,v){const l=this.layers.find(x=>x.id===id);if(l)l.locked=v;}
  setLayerOpacity(v){if(this.activeLayer){this.activeLayer.opacity=v;this.changed('Layer Opacity');}}
  setLayerBlend(v){if(this.activeLayer){this.activeLayer.blend=v;this.changed('Blend Mode');}}
  composite(){const c=canvas(this.doc.width,this.doc.height),x=c.getContext('2d');for(const l of this.layers){if(!l.visible)continue;x.save();x.globalAlpha=l.opacity;x.globalCompositeOperation=l.blend;x.drawImage(l.canvas,0,0);x.restore();}return c;}
  getDataURL(type='image/png',q=.95){return this.composite().toDataURL(type,q);}
  async toBlob(type='image/png',q=.95){return new Promise(ok=>this.composite().toBlob(ok,type,q));}
  fit(){const r=this.wrap.getBoundingClientRect();this.zoom=Math.min((r.width-20)/this.doc.width,(r.height-20)/this.doc.height);if(!Number.isFinite(this.zoom)||this.zoom<=0)this.zoom=1;this.panX=0;this.panY=0;this.onZoom?.(this.zoom);this.render();}
  transform(){const r=this.wrap.getBoundingClientRect(),w=this.doc.width*this.zoom,h=this.doc.height*this.zoom;return{x:(r.width-w)/2+this.panX,y:(r.height-h)/2+this.panY,w,h};}
  tileOffset(tile=this.activeTile){const n=Math.max(0,(Number(tile)||1001)-1001);return{u:n%10,v:Math.floor(n/10)};}
  screenToUV(e){const r=this.overlay.getBoundingClientRect(),t=this.transform(),x=e.clientX-r.left,y=e.clientY-r.top,lu=(x-t.x)/t.w,lv=(y-t.y)/t.h,o=this.tileOffset();return{u:lu+o.u,v:lv+o.v,x:lu*this.doc.width,y:lv*this.doc.height,localU:lu,localV:lv};}
  pointFromUV(u,v){const t=this.transform(),o=this.tileOffset();return{x:t.x+(u-o.u)*t.w,y:t.y+(v-o.v)*t.h};}
  down(e){if(e.button===1||e.button===2||e.altKey){this.panning=true;this.last={sx:e.clientX,sy:e.clientY,px:this.panX,py:this.panY};return;}const p=this.screenToUV(e);if(this.onCoordinates)this.onCoordinates(p.u,p.v);if(this.tool==='select'){this.onUVSelect?.(p.u,p.v);return;}if(this.tool==='eyedropper'){const c=this.composite().getContext('2d').getImageData(Math.max(0,Math.min(this.doc.width-1,Math.floor(p.x))),Math.max(0,Math.min(this.doc.height-1,Math.floor(p.y))),1,1).data;this.color=`#${[c[0],c[1],c[2]].map(v=>v.toString(16).padStart(2,'0')).join('')}`;this.onChange?.({type:'color',color:this.color});return;}if(this.activeLayer?.locked)return;this.dragging=true;this.strokeBefore=this.snapshot();this.last=p;if(this.tool==='fill'){this.fill(p);this.finish('Fill');return;}if(['brush','eraser'].includes(this.tool))this.dot(p,e.pressure||1);}
  move(e){if(this.panning&&this.last){this.panX=this.last.px+(e.clientX-this.last.sx);this.panY=this.last.py+(e.clientY-this.last.sy);this.render();return;}const p=this.screenToUV(e);this.onCoordinates?.(p.u,p.v);if(!this.dragging){if(this.tool==='select')this.onUVHover?.(p.u,p.v);return;}if(['brush','eraser'].includes(this.tool)){this.line(this.last,p,e.pressure||1);this.last=p;}else this.renderPreview(p);}
  up(e){if(this.panning){this.panning=false;this.last=null;return;}if(!this.dragging)return;const p=e?.clientX!=null?this.screenToUV(e):this.last;if(['line','rect','ellipse','lasso','move'].includes(this.tool))this.commitShape(p);this.finish(this.tool==='brush'?'Brush Stroke':this.tool==='eraser'?'Eraser Stroke':this.tool);}
  dot(p,pressure=1){const l=this.activeLayer;if(!l)return;const x=l.canvas.getContext('2d'),s=this.size*(this.pressureSize?Math.max(.15,pressure):1),a=this.opacity*(this.pressureOpacity?Math.max(.05,pressure):1);x.save();if(this.tool==='eraser')x.globalCompositeOperation='destination-out';const g=x.createRadialGradient(p.x,p.y,Math.max(0,s*.5*this.hardness),p.x,p.y,s*.5);g.addColorStop(0,this.tool==='eraser'?`rgba(0,0,0,${a})`:hexToRgba(this.color,a));g.addColorStop(1,'rgba(0,0,0,0)');x.fillStyle=g;x.beginPath();x.arc(p.x,p.y,s*.5,0,Math.PI*2);x.fill();x.restore();this.changed('Paint',false);}
  line(a,b,pressure=1){const d=Math.hypot(b.x-a.x,b.y-a.y),step=Math.max(1,this.size*.12);for(let i=0;i<=d;i+=step){const t=d?i/d:0;this.dot({x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t},pressure);}this.render();}
  fill(p){const l=this.activeLayer,x=l.canvas.getContext('2d'),img=x.getImageData(0,0,l.canvas.width,l.canvas.height),d=img.data,w=l.canvas.width,h=l.canvas.height,sx=Math.max(0,Math.min(w-1,Math.floor(p.x))),sy=Math.max(0,Math.min(h-1,Math.floor(p.y))),i=(sy*w+sx)*4,target=[d[i],d[i+1],d[i+2],d[i+3]],n=parseInt(this.color.slice(1),16),rep=[n>>16&255,n>>8&255,n&255,Math.round(this.opacity*255)];if(target.every((v,k)=>v===rep[k]))return;const q=[[sx,sy]],seen=new Uint8Array(w*h);while(q.length){const [cx,cy]=q.pop(),pi=cy*w+cx;if(cx<0||cy<0||cx>=w||cy>=h||seen[pi])continue;seen[pi]=1;const j=pi*4;if(Math.abs(d[j]-target[0])+Math.abs(d[j+1]-target[1])+Math.abs(d[j+2]-target[2])+Math.abs(d[j+3]-target[3])>32)continue;d[j]=rep[0];d[j+1]=rep[1];d[j+2]=rep[2];d[j+3]=rep[3];q.push([cx+1,cy],[cx-1,cy],[cx,cy+1],[cx,cy-1]);}x.putImageData(img,0,0);}
  renderPreview(p){this.render();const a=this.pointFromUV(this.last.u,this.last.v),b=this.pointFromUV(p.u,p.v);this.octx.save();this.octx.strokeStyle=this.color;this.octx.lineWidth=1.5;this.octx.setLineDash([5,4]);if(this.tool==='line'){this.octx.beginPath();this.octx.moveTo(a.x,a.y);this.octx.lineTo(b.x,b.y);this.octx.stroke();}else if(this.tool==='rect')this.octx.strokeRect(a.x,a.y,b.x-a.x,b.y-a.y);else if(this.tool==='ellipse'){this.octx.beginPath();this.octx.ellipse((a.x+b.x)/2,(a.y+b.y)/2,Math.abs(b.x-a.x)/2,Math.abs(b.y-a.y)/2,0,0,Math.PI*2);this.octx.stroke();}this.octx.restore();}
  commitShape(p){const l=this.activeLayer;if(!l)return;const x=l.canvas.getContext('2d'),a=this.last;x.save();x.strokeStyle=this.color;x.fillStyle=this.color;x.globalAlpha=this.opacity;x.lineWidth=this.size;x.lineCap='round';x.lineJoin='round';if(this.tool==='line'){x.beginPath();x.moveTo(a.x,a.y);x.lineTo(p.x,p.y);x.stroke();}else if(this.tool==='rect')x.strokeRect(a.x,a.y,p.x-a.x,p.y-a.y);else if(this.tool==='ellipse'){x.beginPath();x.ellipse((a.x+p.x)/2,(a.y+p.y)/2,Math.abs(p.x-a.x)/2,Math.abs(p.y-a.y)/2,0,0,Math.PI*2);x.stroke();}x.restore();}
  paintUV(u,v,pressure=1,start=false){const o=this.tileOffset(),p={x:(u-o.u)*this.doc.width,y:(v-o.v)*this.doc.height,u,v};if(start){this.strokeBefore=this.snapshot();this.dragging=true;this.last=p;}if(this.last)this.line(this.last,p,pressure);else this.dot(p,pressure);this.last=p;}
  end3DStroke(){if(this.dragging)this.finish('3D Paint Stroke');}
  finish(label){this.dragging=false;if(this.strokeBefore){const after=this.snapshot();this.history.push({label,before:this.strokeBefore,after,time:Date.now()});if(this.history.length>60)this.history.shift();this.redoStack=[];this.strokeBefore=null;this.onHistory?.(this.history);this.changed(label);}this.last=null;this.render();}
  snapshot(){return this.layers.map(l=>({...l,canvas:cloneCanvas(l.canvas)}));}
  restore(s){this.layers=s.map(l=>({...l,canvas:cloneCanvas(l.canvas)}));if(!this.layers.some(l=>l.id===this.activeLayerId))this.activeLayerId=this.layers[0]?.id;this.changed('Restore',false);}
  undo(){const h=this.history.pop();if(!h)return;this.redoStack.push(h);this.restore(h.before);this.onHistory?.(this.history);}
  redo(){const h=this.redoStack.pop();if(!h)return;this.history.push(h);this.restore(h.after);this.onHistory?.(this.history);}
  addVersion(name=`v${this.versions.length+1}`){this.versions.push({id:crypto.randomUUID?.()||String(Date.now()),name,time:Date.now(),canvas:this.composite()});return this.versions.at(-1);}
  applyVersion(id){const v=this.versions.find(x=>x.id===id);if(v){this.newDocument(v.canvas.width,v.canvas.height,v.canvas);this.changed('Apply Version');}}
  setUVTriangles(tris){this.uvTriangles=tris||[];this.render();}
  setSelectedUV(info){this.selectedUV=info;this.activeTile=info?.udim||this.activeTile;this.render();}
  setHoverUV(info){this.hoverUV=info;this.render();}
  changed(type,notify=true){this.render();if(notify)this.onChange?.({type,canvas:this.composite()});}
  render(){const d=Math.min(devicePixelRatio,2),t=this.transform();this.ctx.setTransform(1,0,0,1,0,0);this.ctx.clearRect(0,0,this.view.width,this.view.height);this.octx.setTransform(1,0,0,1,0,0);this.octx.clearRect(0,0,this.overlay.width,this.overlay.height);this.ctx.scale(d,d);this.octx.scale(d,d);const comp=this.composite();this.ctx.imageSmoothingEnabled=this.zoom<6;this.ctx.drawImage(comp,t.x,t.y,t.w,t.h);for(const tri of this.uvTriangles){if(tri.udim!==this.activeTile)continue;this.drawTri(tri,'rgba(160,170,185,.22)',1);}if(this.hoverUV)this.drawTri(this.hoverUV,'#6ed7ff',1.5);if(this.selectedUV)this.drawTri(this.selectedUV,'#ff7a1a',2.4);}
  drawTri(info,color,width){if(!info?.uvs)return;const pts=info.uvs.map(v=>this.pointFromUV(v.x,v.y));this.octx.save();this.octx.strokeStyle=color;this.octx.lineWidth=width;this.octx.beginPath();this.octx.moveTo(pts[0].x,pts[0].y);this.octx.lineTo(pts[1].x,pts[1].y);this.octx.lineTo(pts[2].x,pts[2].y);this.octx.closePath();this.octx.stroke();this.octx.restore();}
}